# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  functionsSource = "functionsSrc"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/functions/addToNewsletterList"
  to = "/.netlify/functions/addToNewsletterList"
  status = 200
  query = {email = ":email"} # apply this rule for /?path=example

[[redirects]]
  from = "/nicetomeetyou"
  to = "/"
  status = 200

[[redirects]]
  from = "/nicetomeetyou/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/#projects"
  status = 200

[[redirects]]
  from = "/chloe"
  to = "/projects/a-ss21-collection-experience-for-chlo%C3%A9/"
  status = 200
