backend:
  name: git-gateway
  # !! COMMENT IF LOCAL !!
  branch: master
  base_url: https://random.studio
# !! UNCOMMENT IF LOCAL !!
# local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - name: siteInformation
    label: 'Site Information'
    files:
      - file: src/site/settings.md
        label: 'Site settings'
        name: siteSettings
        fields:
          - label: Key
            name: key
            widget: hidden
            default: settings
          - label: 'Site titleÂ§'
            name: title
            widget: string
            default: 'Random Studio'
          - label: 'Description'
            name: description
            widget: text
          - label: 'Twitter handle'
            name: twitterHandle
            widget: string
            default: '@random.studio'
          - label: 'Site URL (base url)'
            name: siteUrl
            widget: string
            default: 'https://random.studio'

  - name: project
    label: Project
    folder: src/pages/projects
    create: true
    identifier_field: title
    slug: '{{slug}}'
    fields:
      - label: 'Template Key'
        name: templateKey
        widget: hidden
        default: Project
      - label: Title
        name: title
        widget: text
      - label: Intro
        name: intro
        buttons:
          - link
        widget: markdown
      - label: 'Priority on homepage'
        name: priority
        required: false
        valueType: float
        widget: nonEmptyStringableNumber
      - label: Content
        name: content
        widget: list
        fields:
          - label: Image
            name: image
            required: false
            widget: image
          - label: Alt tag image
            name: alt
            required: false
            widget: string
          - label: Video
            name: video
            required: false
            collapsed: true
            widget: object
            fields:
              - label: 'Video URL'
                name: url
                required: false
                widget: text
              - label: 'Will autoplay'
                name: autoplay
                required: false
                default: false
                widget: boolean
              - label: 'Show controls'
                name: hasControls
                required: false
                default: false
                widget: boolean
              - label: 'Loop video'
                name: loops
                required: false
                default: true
                widget: boolean
              - label: Muted
                name: isMuted
                required: false
                default: true
                widget: boolean
              - label: 'Always Muted'
                name: isAlwaysMuted
                required: false
                widget: boolean
                default: false
                hint: 'Check this if the video has no audio for example.'
          - label: Carousel
            name: carousel
            widget: list
            types:
              - label: Image
                name: image
                widget: object
                fields:
                  - label: Image
                    name: image
                    required: false
                    widget: image
                  - label: Image Caption
                    name: caption
                    widget: markdown
                    required: false
              - label: Video
                name: video
                required: false
                widget: object
                fields:
                  - label: 'Video URL'
                    name: url
                    required: false
                    widget: text
                  - label: Video Caption
                    name: caption
                    widget: markdown
                    required: false
                  - label: Muted
                    name: isMuted
                    required: false
                    default: true
                    widget: hidden
          - label: Caption
            name: caption
            required: false
            widget: markdown
          - label: Width
            name: width
            required: false
            valueType: float
            widget: nonEmptyStringableNumber
          - label: 'Margin Top'
            name: marginTop
            default: 0
            valueType: float
            widget: nonEmptyStringableNumber
          - label: 'Margin Left'
            name: marginLeft
            default: 0
            valueType: float
            widget: nonEmptyStringableNumber
          - label: 'z-index'
            name: zIndex
            default: 0
            valueType: number
            widget: nonEmptyStringableNumber
      - label: Related Projects
        name: relatedProjects
        widget: object
        required: false
        fields:
          - label: Block Title
            name: blockTitle
            widget: string
            required: false
          - label: Projects
            name: projects
            widget: list
            required: false
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Subtitle
                name: subtitle
                widget: string
                required: false
              - label: Image
                name: image
                widget: image
                required: true
              - label: Project
                name: project
                hint: 'This is the url assignment for the related project'
                widget: relation
                required: true
                collection: 'project'
                searchFields: ['title']
                # valueField: '{{slug}}' Currently not supproted
                valueField: 'title'
                displayFields: ['title']
      - label: Credits
        name: credits
        widget: list
        fields:
          - label: Key
            name: key
            widget: text
          - label: Value
            name: value
            widget: text
      - label: OpenGraph tags
        name: opengraph
        widget: object
        fields:
          - label: 'Title'
            name: ogTitle
            required: false
            valueType: string
            widget: text
          - label: 'Description'
            name: ogDescription
            required: false
            valueType: string
            widget: text
          - label: 'Image'
            name: ogImage
            required: false
            valueType: string
            widget: image

  - name: article
    label: Articles
    folder: src/site/articles
    create: true
    identifier_field: title
    fields:
      - label: Key
        name: key
        widget: hidden
        default: article
      - label: 'Article Title'
        name: title
      - label: quote
        name: quote
        widget: text
      - label: 'Article URL'
        name: articleUrl
        required: false
        widget: string

  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: 'Home Page'
        name: index
        fields:
          - label: 'Template Key'
            name: templateKey
            widget: hidden
            default: index
          - label: 'Logo Position'
            name: layout
            widget: select
            options:
              - { label: center, value: center }
              - { label: Top, value: top }
            default: ['center']
          - label: 'Video URL'
            name: video
            required: true
            widget: text
          - label: Collaboration Credits
            name: collaborationCredits
            required: false
            widget: object
            fields:
              - label: Collaborator
                name: collaborator
                widget: text
              - label: 'Referral URL'
                name: url
                required: false
                widget: text
          - label: Intro
            name: intro
            widget: markdown
          - label: Middle
            name: middle
            widget: markdown
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Homepage Caption
                name: caption
                required: false
                widget: text
              - label: Thumbnail
                name: thumbnail
                widget: object
                fields:
                  - label: Image
                    name: image
                    required: false
                    widget: image
                  - label: 'Video URL'
                    name: video
                    required: false
                    widget: text
                  - label: Width
                    name: width
                    required: false
                    valueType: float
                    widget: nonEmptyStringableNumber
                  - label: 'Margin Top'
                    name: marginTop
                    default: 0
                    valueType: float
                    widget: nonEmptyStringableNumber
                  - label: 'Margin Left'
                    name: marginLeft
                    default: 0
                    valueType: float
                    widget: nonEmptyStringableNumber
              - name: project
                widget: relation
                required: false
                collection: 'project'
                searchFields: ['title']
                valueField: 'title'
                displayFields: ['title']
          - label: Articles
            name: articles
            widget: list
            fields:
              - label: 'Linked Article'
                name: article
                required: false
                widget: relation
                collection: article
                searchFields: [title]
                valueField: title
              - label: 'Article Position'
                name: position
                required: true
                widget: nonEmptyStringableNumber
                hint: 'Set the position of the article here. e.g. 5 will place the article below the 5th project. Will not show if the number is higher than the number of projects.'
          - label: Address
            name: address
            widget: markdown
          - label: 'Phone Number'
            name: phone
            widget: text
          - label: 'Email Address'
            name: email
            widget: text
      - file: src/pages/studio.md
        label: 'Studio page'
        name: studio
        fields:
          - label: 'Template key'
            name: templateKey
            widget: hidden
            default: studio
          - label: Title
            name: title
            widget: string
            default: 'Random Studio'
          - label: 'Intro Block'
            name: introBlock
            widget: list
            fields:
              - label: Copy
                name: copy
                widget: markdown
              - label: Image
                name: image
                widget: image
              - label: Video
                name: video
                widget: file
                hint: 'Adding a video will replace the image'
                required: false
                allow_multiple: false
                media_library:
                  config:
                    multiple: false

          - label: Services
            name: services
            widget: object
            fields:
              - label: Title
                name: title
                widget: text
              - label: 'List of Services'
                name: list
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: text
                  - label: Copy
                    name: copy
                    widget: text
                  - label: Image
                    name: image
                    widget: image

          - label: 'Our Skillset'
            name: skillset
            widget: list
            field:
              label: Skill
              name: skill
              widget: string

          - label: 'Studio impression'
            name: studioImpression
            widget: object
            fields:
              - label: Title
                name: title
                default: 'Studio Impressions'
                widget: text
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                    media_library:
                      config:
                        multiple: true

          - label: 'Job Openings'
            name: jobOpenings
            widget: list
            fields:
              - label: 'Job title'
                name: jobTitle
                widget: string
                default: Job function title
              - label: 'Job URL'
                name: jobURL
                widget: string
                default: https://randomstudio.bamboohr.com/jobs/view.php?id=<ID here>
              - label: 'Job description'
                name: jobDescription
                widget: text
                default: Job description
              - label: 'Show this project live'
                name: jobIsVisible
                widget: boolean
                default: false
